export enum ActionTypes {
  FOUNDATION_SET = 'FOUNDATION_SET',
  FOUNDATION_ADD = 'FOUNDATION_ADD',

  AIRLOCK_OPEN = 'AIRLOCK_OPEN',
  AIRLOCK_CLOSE = 'AIRLOCK_CLOSE',

  SUBSCRIPTION_REMOVE = 'SUBSCRIPTION_REMOVE',
  SUBSCRIPTION_ADD = 'SUBSCRIPTION_ADD',

  ALMONERS_ADD = 'ALMONERS_ADD',
  ALMONERS_REM = 'ALMONERS_REM',

  JANITORS_ADD = 'JANITORS_ADD',

  TAG_ADD = 'TAG_ADD',

  FOLDER_ADD = 'FOLDER_ADD',
}
