export enum GetterTypes {
  AGENT_SUBSCRIPTIONS = 'AGENT_SUBSCRIPTIONS',
  FOUNDATION_BY_PROVIDER = 'FOUNDATION_BY_PROVIDER',
  HOSTED_FOUNDATION_BY_PROVIDER = 'HOSTED_FOUNDATION_BY_PROVIDER',
  HOST_BY_HOST = 'HOST_BY_HOST',
  POST_BY_ID = 'POST_BY_ID',
  HOSTED_FOLDERS_BY_PROVIDER = 'HOSTED_FOLDERS_BY_PROVIDER',
  HOSTED_TAGS_BY_PROVIDER = 'HOSTED_TAGS_BY_PROVIDER',
  HOSTED_FOLDER_BY_DETAILS = 'HOSTED_FOLDER_BY_DETAILS',
}
