export enum MutationTypes {
  FOUNDATIONS_SET = 'FOUNDATIONS_SET',
  FOUNDATIONS_ADD = 'FOUNDATIONS_ADD',

  ALMONERS_ADD = 'ALMONERS_ADD',

  JANITORS_ADD = 'JANITORS_ADD',

  TAG_ADD = 'TAG_ADD',

  SUBSCRIPTION_ADD = 'SUBSCRIPTION_ADD',
  SUBSCRIPTION_REMOVE = 'SUBSCRIPTION_REMOVE',
}
