export enum MutationTypes {
  FOUNDATIONS_SET = 'FOUNDATIONS_SET',
  FOUNDATIONS_ADD = 'FOUNDATIONS_ADD',

  ALMONERS_ADD = 'ALMONERS_ADD',

  SUBSCRIPTION_ADD = 'SUBSCRIPTION_ADD',
  SUBSCRIPTION_REMOVE = 'SUBSCRIPTION_REMOVE',
}
